webtalk_init -webtalk_dir /home/katio/script/github.com/onokatio/itf/COJT/cojt_allin/SIM/tb_sha.sim/sim_1/behav/xsim/xsim.dir/tb_sha256_regtest_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb  2 12:13:34 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "acdaed82-eaf8-48c5-b9e8-774e0be09562" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7c6d11f9177b48b5b4b28a3d3d969c60" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "50" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2000.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "12" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "131 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "173 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "193" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "13" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "250404_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1717353534 -regid "" -xml /home/katio/script/github.com/onokatio/itf/COJT/cojt_allin/SIM/tb_sha.sim/sim_1/behav/xsim/xsim.dir/tb_sha256_regtest_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/katio/script/github.com/onokatio/itf/COJT/cojt_allin/SIM/tb_sha.sim/sim_1/behav/xsim/xsim.dir/tb_sha256_regtest_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/katio/script/github.com/onokatio/itf/COJT/cojt_allin/SIM/tb_sha.sim/sim_1/behav/xsim/xsim.dir/tb_sha256_regtest_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
