# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/design_1_display_0_0.xci
# IP: The module: 'design_1_display_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/src/fifo_48in24out_1024depth/fifo_48in24out_1024depth.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] -quiet

# XDC: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/src/fifo_48in24out_1024depth/fifo_48in24out_1024depth.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/src/fifo_48in24out_1024depth/fifo_48in24out_1024depth_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/hdl/disp_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_display_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/design_1_display_0_0.xci
# IP: The module: 'design_1_display_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/src/fifo_48in24out_1024depth/fifo_48in24out_1024depth.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] -quiet

# XDC: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/src/fifo_48in24out_1024depth/fifo_48in24out_1024depth.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/src/fifo_48in24out_1024depth/fifo_48in24out_1024depth_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/katio/script/github.com/onokatio/itf/COJT/display/display2/display2.srcs/sources_1/bd/design_1/ip/design_1_display_0_0/hdl/disp_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_display_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
