# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/katio/script/github.com/onokatio/itf/COJT/display/disp_ip/src/fifo_48in24out_1024depth/fifo_48in24out_1024depth.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_48in24out_1024depth || ORIG_REF_NAME==fifo_48in24out_1024depth} -quiet] -quiet
